
@startuml
title RBciAD — Package overview
skinparam backgroundColor #FFFFFF
skinparam dpi 150
skinparam shadowing false
skinparam defaultFontName Arial
left to right direction
skinparam packageStyle rectangle
skinparam ArrowColor #222222

package "GUI" {
  class NodeEditor
  class LowCodeCreator
}

package "Engine" {
  class ReactiveEngine
  class RegistryLoader
  class MetricsLogger
}

package "Plugins (Python)" {
  class EEGUniversalReader
  class EEGFilter
  class EEGLiveDisplay
}

package "Polyglot" {
  class PolyglotWrapper
  class ExternalExec <<external>>
}

package "I/O" {
  class DataSources <<external>>  {
    EDF/BDF/GDF/LSL
  }
  class Sinks <<external>> {
    Plots/Web/CSV
  }
}

NodeEditor --> ReactiveEngine
LowCodeCreator --> RegistryLoader
ReactiveEngine --> RegistryLoader

ReactiveEngine --> EEGUniversalReader
EEGUniversalReader --> EEGFilter
EEGFilter --> EEGLiveDisplay

ReactiveEngine --> PolyglotWrapper
PolyglotWrapper ..> ExternalExec

DataSources --> EEGUniversalReader
EEGLiveDisplay --> Sinks
ReactiveEngine --> MetricsLogger
MetricsLogger --> Sinks
@enduml
